name = "DocumenterCitations"
uuid = "daee34ce-89f3-4625-b898-19384cb65244"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "1.0.0"

[deps]
Bibliography = "f1be7e48-bf82-45af-a471-ae754a193061"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
Bibliography = "^0.2"
Documenter = "0.27"
OrderedCollections = "1"
julia = "^1.6"
